services:
  - type: web
    name: mini-erp
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: APP_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        sync: false
      - key: TEST_DB_TOKEN
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
