services:
  - type: web
    name: mini-erp
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Tristan9Tristan10@db.lfbosnucnokjjluotoup.supabase.co:5432/postgres
      - key: APP_ENV
        value: production
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        value: kdc_mini_erp_2026_prod_secret_key_x9z
      - key: WEB_CONCURRENCY
        value: 1
